import { Poppins } from "next/font/google";
import "./globals.css";

import { Toaster } from "../components/ui/sonner";
import NextTopLoader from "nextjs-toploader";

import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import ReactQueryProvider from "@/context/ReactQueryProvider";
import SessionWrapper from "@/context/SessionWrapper";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "900"],
});

export const metadata = {
  title: "Food Cheetah - Food Ordering App",
  description: "Generated by create next app",
  icons: {
    icon: "/Chester-Cheetah-LOGO.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <SessionWrapper>
          <ReactQueryProvider>
            <NextTopLoader color="#FFBF00" />
            <Navbar />
            <div>{children}</div>
            <Toaster visibleToasts={1} richColors theme="light" />
            <Footer />
          </ReactQueryProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
